### ISSUE TITLE
[建议] 方法名跟autojs 或者EasyClick 同步

### ISSUE THREAD

**Issue by photkey** [5tiaowu/MagicHands#2]
如果方法名跟autojs或者EasyClick同步（相同功能的方法），可以更方便的把autojs脚本迁移过来，而且对于之前熟悉autojs、第一次接触MH的用户来说，学习成本也更低，直接就可以上手写代码了。

**Comment by ximengxuan** [comment]
同意。建议跟autojs同步。EasyClick的命名不太规范

**Comment by topcoco** [comment]
会慢慢同步
